### ISSUE TITLE
Canceling object spams gcode

### ISSUE THREAD

**Issue by NovaViper** [paukstelis/Octoprint-Cancelobject#46] opened 2020-01-13 17:45 UTC
Hey. I added in some gcode that whenever an object gets canceled, it makes the printer raise up by 10mm to avoid hitting any other object that remains on the bed. However, when I go and cancel one object, it seems to continuously spam the gcode I have set, which causes my printer to keep on raising the gantry until it smacks into my frame. I'm running Octoprint 1.3.12 on OctoPi 0.16.0 with the latest version of CancelObjects. Could you please fix this?
This is the gcode here.
![image](https://user-images.githubusercontent.com/7191115/72278612-fdd5d680-35f9-11ea-8527-1908601278dd.png)

And this is the terminal showing the spamming
![image](https://user-images.githubusercontent.com/7191115/72278635-07f7d500-35fa-11ea-9331-f6aec4341d8b.png)

**Comment by paukstelis** [comment] 2020-01-13 18:00
I will look into this. For clarification, where are you readjusting the Z-height after you lift?

**Comment by paukstelis** [comment] 2020-01-13 18:44
If you can, uninstall and reinstall from this URL to test: https://github.com/paukstelis/Octoprint-Cancelobject/archive/0.4.1.zip

**Comment by NovaViper** [comment] 2020-01-13 19:30
@paukstelis It still spams the gcode. And it doesn't install 0.4.1 but 0.4.0 instead

**Comment by paukstelis** [comment] 2020-01-13 19:33
Yes, it is still tagged as 0.4.0. It doesn't spam any gcode in my tests. Perhaps try removing your M85s and see what happens.

**Comment by paukstelis** [comment] 2020-01-13 19:43
What printer/firmware? What hardware are you using to run OctoPrint?  I've tested with the same commands you have and I don't see an issue. Can you attach your gcode?

**Comment by NovaViper** [comment] 2020-01-13 19:44
Creality Ender 3 with Marlin 2.0 on the SKR V1.3

⁣Get BlueMail for Android ​

**Comment by NovaViper** [comment] 2020-01-13 19:54
For running Octoprint, I'm using the raspberry pi 3B+

And the screen shot I sent is the gcode in using for the command 

⁣Get BlueMail for Android ​

**Comment by NovaViper** [comment] 2020-01-13 20:07
Here's the gcode

**Comment by NovaViper** [comment] 2020-01-13 21:11
Here's the part im testing it on. https://gist.github.com/NovaViper/bd4c97bb50bbafee92e336a58d8ad05e

And I went and reinstalled the plugin twice, but it still keeps spamming the gcode

**Comment by paukstelis** [comment] 2020-01-13 21:40
I am fairly certain this is a firmware compatibility issue. One of these commands is probably a queue-jumper in Marlin 2.0 that leads to the loop. See what happens when you remove all M85s from before and after gcode.

**Comment by NovaViper** [comment] 2020-01-13 21:47
Nope, didn't fix it

**Comment by paukstelis** [comment] 2020-01-13 21:50
It won't happen in the terminal because of how the command buffer works. This certainly doesn't reproduce on my Prusa. I'll flash the latest Marlin 2.0 on another printer and see what happens.

**Comment by paukstelis** [comment] 2020-01-14 02:22
I flashed latest Marlin 2.0 (bugfix) on a printer and could not reproduce this issue. This leads me to believe that it is not something related to the plugin, but is either firmware or hardware or perhaps some combination. Wish I could tell you more, but I can't fix a problem I can't see.

**Comment by NovaViper** [comment] 2020-01-14 03:24
Idk if it will help any, but I do have Action commands turned on in the firmware. And the marlin 2.0 im using is the full release version (the non-bugfix version)

**Comment by paukstelis** [comment] 2020-01-24 16:34
When you are working with this, are you cancelling just a single object, or are there multiple objects that get cancelled. I continued to test this and the only time I can reproduce with your before gcode is when I have multiple objects and I cancel several in a row.  In that case it does do multiple z lifts since it is hitting multiple cancelled objects.

**Comment by NovaViper** [comment] 2020-01-25 03:21
The very first time, I did cancel multiple objects. I can't remember the second time around though. I'm not at my house to verify this unfortunately

**Comment by paukstelis** [comment] 2020-07-15 20:35
Without more to work with here, I am going to close this for now. Please let me know if you are still experiencing this issue.

**Closed by paukstelis** 2020-07-15 20:35 UTC
